### ISSUE TITLE
Plone Training not starting on Heroku

### ISSUE THREAD

**Issue by sanmell** [collective/training-sandbox#10]
I've just clicked at the button to build, chose a name and start deploying. 
This is the TXT from the error: [error Plnoe Heroku.txt](https://github.com/collective/training-sandbox/files/1616471/error.Plnoe.Heroku.txt) (sorry de mispelling)

I think the part that matters in this error is: 

> VersionConflict: (zc.buildout 2.10.0 (/tmp/build_a999ff1b0dadef0ff9ab0cd6fe96aa2b/collective-training-sandbox-8839db8/eggs/zc.buildout-2.10.0-py2.7.egg), Requirement.parse('zc.buildout==2.9.5'))
 !     Push rejected, failed to compile Plone app.
 !     Push

**Comment by bstevenkrause** [comment]
Same error here.

**Comment by sanmell** [comment]
Now is another error:

>  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: ('File is not a zip file', 'Maybe /tmp/tmp6LVICx/setuptools-33.1.1.zip is corrupted, delete it and try again.')
 !     Push rejected, failed to compile Plone app.
 !     Push failed
