### ISSUE TITLE
Heroku Build Failure

### ISSUE THREAD

**Issue by joshuazong** [collective/training-sandbox#5]
Hello,

Receiving an App creation failed error when attempting to deploy.  Attached is a .txt file with the Build Log error.  Let me know how I may correct the error or if there is any further information I may supply.
[buildAppLog.txt](https://github.com/collective/training-sandbox/files/922964/buildAppLog.txt)

Thanks,
Joshua

**Comment by malloxpb** [comment]
Hey, I think my solution can solve this problem. Thank you
https://github.com/nctl144/training-sandbox

**Comment by macagua** [comment]
@nctl144 thanks you!

**Comment by joshuazong** [comment]
Yep, that works fine just fine for 5.0.6

Thanks!

**Comment by samob** [comment]
Hi, I have tried to deploy Plone on Heroku and got this error on end:
```
Version and requirements information containing plone.schema:

  [versions] constraint on plone.schema: 1.0.0

  Requirement of plone.restapi: plone.schema>=1.2.0

While:

  Installing instance.

Error: The requirement ('plone.schema>=1.2.0') is not allowed by your [versions] constraint (1.0.0)

 !     Push rejected, failed to compile Plone app.

 !     Push failed
```
Whole log in attached txt file.

[heroku-plone-buildout.txt](https://github.com/collective/training-sandbox/files/2238781/heroku-plone-buildout.txt)

**Comment by witekdev** [comment]
@samob Fixed, tested to be working with 5.0.8

**Comment by witekdev** [comment]
@samob now updated to 5.1.2

**Comment by samob** [comment]
Thanks, it works
